autotools update.
git-svn-id: svn+ssh://svn.code.sf.net/p/marsyas/code/trunk@2359 0e98fd9d-079e-457f-9c5c-d482923f975d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5465,6 +5465,10 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
 #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
 _ACEOF
 
+else
+  { { echo "$as_me:$LINENO: error: Cannot find ALSA headers" >&5
+echo "$as_me: error: Cannot find ALSA headers" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 done
