automatic update of autotools.
git-svn-id: svn+ssh://svn.code.sf.net/p/marsyas/code/trunk@1988 0e98fd9d-079e-457f-9c5c-d482923f975d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_VERSION='0.2.12'
 PACKAGE_STRING='marsyas 0.2.12'
 PACKAGE_BUGREPORT='gtzan@cs.uvic.ca'
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE ac_aux_dir RANLIB ac_ct_RANLIB DISTRIBUTED MADLIB OGGLIB MslLibs MATLABLIBS QT_PRESENT_TRUE QT_PRESENT_FALSE Audio Libs INCLUDES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE ac_aux_dir RANLIB ac_ct_RANLIB DISTRIBUTED MADLIB OGGLIB MslLibs MATLABLIBS qmake QT_PRESENT_TRUE QT_PRESENT_FALSE Audio Libs INCLUDES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -849,8 +849,6 @@ Optional Packages:
   --with-readline         Readline functionality for Marsyas scriping language
                           (MSL)
   --with-matlab           Activate MATLAB engine interface
-  --with-qt-dir=/path/to/Qt
-                          Path to Qt 4.1.0 or later.
 
 Some influential environment variables:
   CC          C compiler command
@@ -3855,48 +3853,46 @@ _ACEOF
 esac
 
 
-### check for qmake.  Code from
-# http://trac.vidalia-project.net/browser/trunk/configure.in
-# Find Qt or use one specified to ./configure
-
-# Check whether --with-qt-dir or --without-qt-dir was given.
-if test "${with_qt_dir+set}" = set; then
-  withval="$with_qt_dir"
-  QTPATHS="$withval"
+# Extract the first word of "qmake", so it can be a program name with args.
+set dummy qmake; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_qmake+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-   # There can be multiple versions of Qt under these directories
-    QTPATHS="/usr/local/Trolltech /usr/Trolltech /usr"
-    VERLIST=`ls -rm /usr/local/Trolltech/ 2> /dev/null | sed -e s/,//`
-    for ver in $VERLIST; do
-      QTPATHS="$QTPATHS /usr/local/Trolltech/$ver"
-    done
-    VERLIST=`ls -rm /usr/Trolltech/ 2> /dev/null | sed -e s/,//`
-    for ver in $VERLIST; do
-      QTPATHS="$QTPATHS /usr/Trolltech/$ver"
-    done
-
-fi;
-
-echo "$as_me:$LINENO: checking for Qt >= 4.1.0" >&5
-echo $ECHO_N "checking for Qt >= 4.1.0... $ECHO_C" >&6
-for path in $QTPATHS; do
-  # "qmake" is sometimes spelled "qmake-qt4"
-  if test -x $path/bin/qmake-qt4; then
-    QMAKE=$path/bin/qmake-qt4
-  else
-    if test -x $path/bin/qmake; then
-      QMAKE=$path/bin/qmake
-    fi
+  if test -n "$qmake"; then
+  ac_cv_prog_qmake="$qmake" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_qmake="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
   fi
-  if test x$QMAKE != x; then
-    # Ask qmake if we have the right version
-    QTVERSION=`$QMAKE -query QT_VERSION`
-    case $QTVERSION in
-      4.1.*|4.2.*|4.3.*)
-        QTDIR=`$QMAKE -query QT_INSTALL_PREFIX`
+done
+done
+
+  test -z "$ac_cv_prog_qmake" && ac_cv_prog_qmake="no"
+fi
+fi
+qmake=$ac_cv_prog_qmake
+if test -n "$qmake"; then
+  echo "$as_me:$LINENO: result: $qmake" >&5
+echo "${ECHO_T}$qmake" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test $qmake = yes; then
 
 
-if test "x$QMAKE" != ""; then
+if true; then
   QT_PRESENT_TRUE=
   QT_PRESENT_FALSE='#'
 else
@@ -3904,13 +3900,18 @@ else
   QT_PRESENT_FALSE=
 fi
 
-        break
-        ;;
-      *);;
-    esac
-  fi
-done
+else
 
+
+if false; then
+  QT_PRESENT_TRUE=
+  QT_PRESENT_FALSE='#'
+else
+  QT_PRESENT_TRUE='#'
+  QT_PRESENT_FALSE=
+fi
+
+fi
 
 
 
@@ -4059,6 +4060,13 @@ if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"AMDEP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${QT_PRESENT_TRUE}" && test -z "${QT_PRESENT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"QT_PRESENT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"QT_PRESENT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4666,6 +4674,7 @@ s,@MADLIB@,$MADLIB,;t t
 s,@OGGLIB@,$OGGLIB,;t t
 s,@MslLibs@,$MslLibs,;t t
 s,@MATLABLIBS@,$MATLABLIBS,;t t
+s,@qmake@,$qmake,;t t
 s,@QT_PRESENT_TRUE@,$QT_PRESENT_TRUE,;t t
 s,@QT_PRESENT_FALSE@,$QT_PRESENT_FALSE,;t t
 s,@Audio@,$Audio,;t t
